//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IEduxJsAdapter
{
    handleEduxEvent(eduxEventKey: string) : Promise<void>;
    setEventHandlerJs(value: string) : Promise<void>;
    resetEduxRoot() : Promise<void>;
}
export interface IJsUtilsAdapter
{
    blur() : Promise<void>;
    scrollToBottom(elementId: string) : Promise<void>;
}
